### ISSUE TITLE
alive_progress

### ISSUE THREAD

**Issue by sasholy** [sanjai-AK47/ShodanX#4]
hello
I have an error.
`[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page.. `
thx.

**Comment by sanjai-AK47** [comment]
Hey @sasholy ,
Try command `pip install alive_progress`

**Comment by sasholy** [comment]
doesn't work
`shodanx domain -d testphp.vulnweb.com
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page.. `

**Comment by sanjai-AK47** [comment]
Hey @sasholy ,
Try with sudo I hope now it will resolve

**Comment by sasholy** [comment]
> Hey @sasholy , Try with sudo I hope now it will resolve

I tried it, it doesn't work.

**Comment by sanjai-AK47** [comment]
Hey @sasholy ,
Use commands
`sudo pip uninstall shodanx`
`sudo pip install shodanx`
`sudo pip install alive_progress`

**Comment by sanjai-AK47** [comment]
Hey Also upgrade your pip to latest version

**Comment by sasholy** [comment]
> `sudo pip uninstall shodanx`
> `sudo pip install shodanx`
> `sudo pip install alive_progress`

sudo pip3 uninstall shodanx
sudo pip3 install shodanx
sudo pip3 install alive_progress

thank you very much, updated everything, everything works

**Comment by sanjai-AK47** [comment]
Hey @sasholy ,
Your Welcome and Happy that now shodanx working for you and also Im closing this issue now :)
