### ISSUE TITLE
Installation Problem on Parrot Security OS (Linux parrot 6.5.0-13parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1parrot1)

### ISSUE THREAD

**Issue by Th3BlackHol3** [sanjai-AK47/ShodanX#7]
Hello,
Here I faced an issue when I tried to install this tool on My machine, I am just putting the output that I got from installation time, the issue is given below.

```
$ pip install git+https://github.com/sanjai-AK47/ShodanX
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

As I told My friend to install this tool, He tried to install shodanx to Kali NetHunter and It was working perfectly! I must say this is an awesome tool for Recon. Thanks!.

**Comment by sanjai-AK47** [comment]
Hello @Th3BlackHol3 ,
Thanks for your wonderful feedbacks and thanks for providing the messages while installation,
please check your python version is latest, if its in latest version please try this command to install:
```
pip install shodanx --break-system-packages
```

try the above command and please inform me back if the installation successfull or not.

**Comment by Th3BlackHol3** [comment]
Hi @sanjai-AK47 
Installed successfully after breaking the system packages, but after giving command $ shodanx this issue occurred. Here is the issue below:

```
$ shodanx
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page.. 
```

After that, to solve this issue I install the 'alive_progress' module, 

```
pip install alive-progress
```

If it does not work, Try with "--break-system-packages",

```
pip install alive-progress --break-system-packages
```

It will  work surely! Thanks.
